name: Shell commands

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - master
  push:

env:
  BUILD_ENV: |
    ${{ 
      contains( github.ref, '/prd/' ) &&
        "prd" ||
      contains( github.ref, '/stg/' ) &&
        "stg" ||
      "dev"
    }}
  BUILD_SECRET: |
    ${{ 
      contains( github.ref, '/prd/' ) &&
        secrets.PRD_BUILD_SECRET ||
      contains( github.ref, '/stg/' ) &&
        secrets.STG_BUILD_SECRET ||
      secrets.DEV_BUILD_SECRET
    }}

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo Envs
        run: |
          echo command1: ${BUILD_ENV}
          echo command1: ${BUILD_SECRET}
  
  run-shell-command-2:
    runs-on: ubuntu-latest
    steps:
      - name: echo Envs
        run: |
          echo command2: ${BUILD_ENV}
          echo command2: ${BUILD_SECRET}
